---
# tasks file for logstash
 
- name: Logstash
  docker_container:
    volumes:
      - /mnt/vol1:/mnt/data
  vars:
    logstash_user: "logstash"
    logstash_group: "logstash"
    logstash_service_name: "logstash"
    logstash_image: "logstash:7.2.1"
    logstash_container_name: "logstash"
    logstash_command: '["-f", "/etc/logstash/logstash.conf", "-w", "1"]'
    
    logstash_compose_files_path: "/etc/compose-files"
    
    logstash_monitoring_enabled: true
    logtash_exporter_image: "sequra/logstash_exporter:v0.1.3"
    logstash_exporter_command: "--web.listen-address=:9198 --logstash.endpoint=http://{{ logstash_service_name }}:9600"
    logstash_pipeline: |
      input {
      }
      output {
      }
    logstash_envs: {}
  roles:
    - geerlingguy.docker
    - ansible-role-logstash-in-docker
  