---
# tasks file for elastic
- name: Elasticsearch Custom Configuration
  vars:
    es_data_dirs:
      - "/mnt/data"
    es_log_dir: "/opt/elasticsearch/logs"
    es_config:
      node.name: "node1"
      cluster.name: "custom-cluster"
      discovery.seed_hosts: "localhost:9301"
      http.port: 9201
      transport.port: 9301
      node.data: false
      node.master: true
      bootstrap.memory_lock: true
    es_heap_size: 2g
    es_api_port: 9201
